Two Solved. 56 and Color Bands
wholepixel/solving-sol pull request #81
Opened 2022-03-30 16:08 UTC by MissChervinsky

2022-03-30 16:08 UTC, MissChervinsky commented
email at chervinsky@voorhees.k12.nj.us

2024-02-26 22:21 UTC, doolittle commented on 056/Chervinsky
@MissChervinsky can you rename this file from "Chervinsky" to "MissChervinsky" — your full username?

2024-02-26 22:22 UTC, doolittle commented on ColorBands
@MissChervinsky since the Color Bands piece isn't one of LeWitt's numbered instructional works, I don't think it fits with this project. Can you remove it? Great work thought!

2024-02-26 22:23 UTC, doolittle requested changes
Please rename file to match your username, and remove ColorBands solution. Thank you!

2025-04-02 05:31 UTC, closed without merging